import type { ToolDefinition } from "./types";

/**
 * VisionQuest Tool Registry
 *
 * Single source of truth for every platform capability.
 * Each entry declares permissions, budgets, audit levels, and feature gating.
 *
 * Naming convention: "namespace.action" (e.g., "sage.chat", "goals.create")
 */
export const TOOLS: readonly ToolDefinition[] = [
  // ─── Auth Namespace ──────────────────────────────────────────────────────────

  {
    id: "auth.login",
    namespace: "auth",
    name: "Login",
    description: "Authenticate a student or teacher with email and password",
    endpoint: { method: "POST", path: "/api/auth/login" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    rateLimit: { maxPerHour: 20 },
    enabled: true,
    tags: ["auth", "public"],
  },
  {
    id: "auth.register_teacher",
    namespace: "auth",
    name: "Register Teacher",
    description: "Create a new teacher account using the TEACHER_KEY",
    endpoint: { method: "POST", path: "/api/auth/register-teacher" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    rateLimit: { maxPerHour: 5 },
    enabled: true,
    tags: ["auth", "onboarding"],
  },
  {
    id: "auth.logout",
    namespace: "auth",
    name: "Logout",
    description: "End the current session and clear auth cookies",
    endpoint: { method: "DELETE", path: "/api/auth/session" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["auth"],
  },
  {
    id: "auth.forgot_password",
    namespace: "auth",
    name: "Forgot Password",
    description: "Initiate password reset flow via security questions",
    endpoint: { method: "POST", path: "/api/auth/forgot-password" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    rateLimit: { maxPerHour: 5 },
    enabled: true,
    tags: ["auth", "security"],
  },
  {
    id: "auth.reset_password",
    namespace: "auth",
    name: "Reset Password",
    description: "Reset password after verifying security questions",
    endpoint: { method: "POST", path: "/api/auth/reset-password" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    rateLimit: { maxPerHour: 5 },
    enabled: true,
    tags: ["auth", "security"],
  },
  {
    id: "auth.reset_password_questions",
    namespace: "auth",
    name: "Verify Security Questions",
    description: "Verify security question answers for password reset",
    endpoint: { method: "POST", path: "/api/auth/reset-password/questions" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    rateLimit: { maxPerHour: 10 },
    enabled: true,
    tags: ["auth", "security"],
  },
  {
    id: "auth.session",
    namespace: "auth",
    name: "Get Session",
    description: "Return the current authenticated session details",
    endpoint: { method: "GET", path: "/api/auth/session" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["auth"],
  },
  {
    id: "auth.google_oauth",
    namespace: "auth",
    name: "Google OAuth",
    description: "Initiate Google OAuth sign-in flow",
    endpoint: { method: "GET", path: "/api/auth/google" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["auth", "oauth"],
  },
  {
    id: "auth.google_oauth_callback",
    namespace: "auth",
    name: "Google OAuth Callback",
    description: "Handle Google OAuth callback and create/link session",
    endpoint: { method: "GET", path: "/api/auth/google/callback" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["auth", "oauth"],
  },
  {
    id: "auth.security_questions_get",
    namespace: "auth",
    name: "Get Security Questions",
    description: "Retrieve stored security questions for the current user",
    endpoint: { method: "GET", path: "/api/settings/security-questions" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["auth", "security", "settings"],
  },
  {
    id: "auth.security_questions_set",
    namespace: "auth",
    name: "Set Security Questions",
    description: "Store security questions and answers for password recovery",
    endpoint: { method: "POST", path: "/api/settings/security-questions" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["auth", "security", "settings"],
  },

  // ─── Sage Namespace (AI-powered) ─────────────────────────────────────────────

  {
    id: "sage.chat",
    namespace: "sage",
    name: "Sage Chat",
    description: "Send a message to the Sage AI coach and receive a streamed response",
    endpoint: { method: "POST", path: "/api/chat/send" },
    requiredRoles: ["student", "teacher", "admin"],
    tokenBudget: 4000,
    auditLevel: "full",
    rateLimit: { maxPerHour: 60 },
    enabled: true,
    requiresContext: ["conversation", "studentProfile", "goals"],
    tags: ["ai", "chat", "core"],
  },
  {
    id: "sage.conversations",
    namespace: "sage",
    name: "List Conversations",
    description: "List all Sage conversations for the current user",
    endpoint: { method: "GET", path: "/api/chat/conversations" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["chat"],
  },
  {
    id: "sage.history",
    namespace: "sage",
    name: "Chat History",
    description: "Retrieve message history for a specific conversation",
    endpoint: { method: "GET", path: "/api/chat/history" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["chat"],
  },
  {
    id: "sage.warmup",
    namespace: "sage",
    name: "Sage Context Warmup",
    description: "Pre-warm the student base-context cache so the first Sage message is fast",
    endpoint: { method: "GET", path: "/api/chat/warmup" },
    requiredRoles: ["student"],
    auditLevel: "none",
    rateLimit: { maxPerHour: 60 },
    enabled: true,
    tags: ["chat", "performance"],
  },
  {
    id: "sage.goal_extraction",
    namespace: "sage",
    name: "Goal Extraction",
    description: "AI extracts actionable goals from a Sage conversation",
    requiredRoles: ["student", "teacher", "admin"],
    tokenBudget: 2000,
    auditLevel: "basic",
    enabled: true,
    requiresContext: ["conversation"],
    tags: ["ai", "goals", "extraction"],
  },
  {
    id: "sage.mood_extraction",
    namespace: "sage",
    name: "Mood Extraction",
    description: "AI extracts emotional wellness scores from a conversation",
    requiredRoles: ["student", "teacher", "admin"],
    tokenBudget: 1000,
    auditLevel: "basic",
    enabled: true,
    requiresContext: ["conversation"],
    tags: ["ai", "wellness", "extraction"],
  },
  {
    id: "sage.discovery_extraction",
    namespace: "sage",
    name: "Career Discovery Extraction",
    description: "AI extracts career interest signals from a conversation",
    requiredRoles: ["student", "teacher", "admin"],
    tokenBudget: 2000,
    auditLevel: "basic",
    enabled: true,
    requiresContext: ["conversation"],
    tags: ["ai", "career", "extraction"],
  },
  {
    id: "sage.summarize",
    namespace: "sage",
    name: "Conversation Summary",
    description: "AI summarizes a long conversation for context compression",
    requiredRoles: ["student", "teacher", "admin"],
    tokenBudget: 2000,
    auditLevel: "basic",
    enabled: true,
    requiresContext: ["conversation"],
    tags: ["ai", "chat"],
  },
  {
    id: "sage.resume_assist",
    namespace: "sage",
    name: "Resume Assist",
    description: "AI generates or refines resume content based on student profile",
    endpoint: { method: "POST", path: "/api/resume/assist" },
    requiredRoles: ["student"],
    tokenBudget: 3000,
    auditLevel: "basic",
    rateLimit: { maxPerHour: 8 },
    enabled: true,
    requiresContext: ["resume", "certifications", "goals"],
    tags: ["ai", "resume", "career"],
  },
  {
    id: "sage.resume_extract",
    namespace: "sage",
    name: "Resume Extract",
    description: "AI parses an uploaded resume file into structured data",
    endpoint: { method: "POST", path: "/api/resume/upload" },
    requiredRoles: ["student"],
    tokenBudget: 2000,
    auditLevel: "basic",
    rateLimit: { maxPerHour: 5 },
    enabled: true,
    tags: ["ai", "resume", "extraction"],
  },
  {
    id: "sage.snippets_list",
    namespace: "sage",
    name: "Sage Snippets List",
    description: "List AI-generated Sage conversation snippets for teacher review",
    endpoint: { method: "GET", path: "/api/teacher/sage-snippets" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["ai", "teacher"],
  },
  {
    id: "sage.snippets_create",
    namespace: "sage",
    name: "Create Sage Snippet",
    description: "Save a notable conversation snippet from Sage for review",
    endpoint: { method: "POST", path: "/api/teacher/sage-snippets" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["ai", "teacher"],
  },
  {
    id: "sage.snippets_update",
    namespace: "sage",
    name: "Update Sage Snippet",
    description: "Edit an existing Sage conversation snippet",
    endpoint: { method: "PATCH", path: "/api/teacher/sage-snippets" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["ai", "teacher"],
  },
  {
    id: "sage.snippets_delete",
    namespace: "sage",
    name: "Delete Sage Snippet",
    description: "Remove a Sage conversation snippet",
    endpoint: { method: "DELETE", path: "/api/teacher/sage-snippets" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["ai", "teacher"],
  },
  {
    id: "sage.context_documents",
    namespace: "sage",
    name: "Sage Context Documents",
    description: "Manage RAG grounding documents for Sage AI knowledge base",
    endpoint: { method: "GET", path: "/api/teacher/documents/sage-context" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["ai", "teacher", "rag"],
  },
  {
    id: "sage.context_documents_update",
    namespace: "sage",
    name: "Update Sage Context Document",
    description: "Upload or modify a RAG grounding document for Sage",
    endpoint: { method: "PATCH", path: "/api/teacher/documents/sage-context" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["ai", "teacher", "rag"],
  },

  // ─── Goals Namespace ─────────────────────────────────────────────────────────

  {
    id: "goals.list",
    namespace: "goals",
    name: "List Goals",
    description: "Retrieve all goals for the current student",
    endpoint: { method: "GET", path: "/api/goals" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["goals", "core"],
  },
  {
    id: "goals.create",
    namespace: "goals",
    name: "Create Goal",
    description: "Create a new goal for the current student",
    endpoint: { method: "POST", path: "/api/goals" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["goals", "core"],
  },
  {
    id: "goals.update",
    namespace: "goals",
    name: "Update Goal",
    description: "Update an existing goal (status, description, progress)",
    endpoint: { method: "PATCH", path: "/api/goals/:id" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["goals", "core"],
  },
  {
    id: "goals.resources",
    namespace: "goals",
    name: "Goal Resources",
    description: "List linked resources for a specific goal",
    endpoint: { method: "GET", path: "/api/goals/:id/resources" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["goals", "resources"],
  },
  {
    id: "goals.resource_link_create",
    namespace: "goals",
    name: "Link Resource to Goal",
    description: "Attach a learning resource link to a student goal (teacher only)",
    endpoint: { method: "POST", path: "/api/goal-resource-links" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["goals", "resources", "teacher"],
  },
  {
    id: "goals.resource_link_update",
    namespace: "goals",
    name: "Update Goal Resource Link",
    description: "Edit an existing goal-resource link",
    endpoint: { method: "PATCH", path: "/api/goal-resource-links/:id" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["goals", "resources"],
  },
  {
    id: "goals.confirm",
    namespace: "goals",
    name: "Confirm Goal",
    description: "Teacher confirms or reviews a student-created goal",
    endpoint: { method: "PATCH", path: "/api/teacher/students/:id/goals/:goalId" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["goals", "teacher", "review"],
  },
  {
    id: "goals.pathway_suggestions",
    namespace: "goals",
    name: "Goal Pathway Suggestions",
    description: "Get AI-suggested pathways for a specific student goal",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/goals/:goalId/pathway-suggestions" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["goals", "ai", "teacher"],
  },

  // ─── Orientation Namespace ───────────────────────────────────────────────────

  {
    id: "orientation.progress",
    namespace: "orientation",
    name: "Orientation Progress",
    description: "Get or update current student orientation progress",
    endpoint: { method: "GET", path: "/api/orientation" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["orientation", "onboarding"],
  },
  {
    id: "orientation.step_update",
    namespace: "orientation",
    name: "Update Orientation Step",
    description: "Mark an orientation step as completed or update responses",
    endpoint: { method: "POST", path: "/api/orientation" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["orientation", "onboarding"],
  },
  {
    id: "orientation.complete",
    namespace: "orientation",
    name: "Complete Orientation",
    description: "Mark the entire orientation wizard as completed",
    endpoint: { method: "POST", path: "/api/orientation/complete" },
    requiredRoles: ["student"],
    auditLevel: "full",
    enabled: true,
    tags: ["orientation", "onboarding", "milestone"],
  },
  {
    id: "orientation.items_list",
    namespace: "orientation",
    name: "List Orientation Items",
    description: "Teacher view of all orientation step configurations",
    endpoint: { method: "GET", path: "/api/teacher/orientation" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["orientation", "teacher"],
  },
  {
    id: "orientation.items_create",
    namespace: "orientation",
    name: "Create Orientation Item",
    description: "Add a new orientation step to the wizard",
    endpoint: { method: "POST", path: "/api/teacher/orientation" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["orientation", "teacher", "config"],
  },
  {
    id: "orientation.items_update",
    namespace: "orientation",
    name: "Update Orientation Item",
    description: "Modify an existing orientation step configuration",
    endpoint: { method: "PUT", path: "/api/teacher/orientation" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["orientation", "teacher", "config"],
  },
  {
    id: "orientation.items_delete",
    namespace: "orientation",
    name: "Delete Orientation Item",
    description: "Remove an orientation step from the wizard",
    endpoint: { method: "DELETE", path: "/api/teacher/orientation" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["orientation", "teacher", "config"],
  },

  // ─── Certifications Namespace ────────────────────────────────────────────────

  {
    id: "certifications.list",
    namespace: "certifications",
    name: "List Certifications",
    description: "Retrieve available certifications and student progress",
    endpoint: { method: "GET", path: "/api/certifications" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["certifications", "core"],
  },
  {
    id: "certifications.submit",
    namespace: "certifications",
    name: "Submit Certification",
    description: "Student submits proof of a completed certification",
    endpoint: { method: "POST", path: "/api/certifications" },
    requiredRoles: ["student"],
    auditLevel: "full",
    enabled: true,
    tags: ["certifications", "core", "evidence"],
  },
  {
    id: "certifications.teacher_list",
    namespace: "certifications",
    name: "Teacher Certifications List",
    description: "Teacher view of all student certification submissions",
    endpoint: { method: "GET", path: "/api/teacher/certifications" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["certifications", "teacher"],
  },
  {
    id: "certifications.approve",
    namespace: "certifications",
    name: "Approve Certification",
    description: "Teacher approves or rejects a student certification submission",
    endpoint: { method: "PUT", path: "/api/teacher/certifications" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["certifications", "teacher", "review"],
  },
  {
    id: "certifications.templates_create",
    namespace: "certifications",
    name: "Create Certification Template",
    description: "Teacher creates a new certification template definition",
    endpoint: { method: "POST", path: "/api/teacher/certifications" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["certifications", "teacher", "config"],
  },
  {
    id: "certifications.templates_delete",
    namespace: "certifications",
    name: "Delete Certification Template",
    description: "Teacher removes a certification template",
    endpoint: { method: "DELETE", path: "/api/teacher/certifications" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["certifications", "teacher", "config"],
  },
  {
    id: "certifications.credly_badges",
    namespace: "certifications",
    name: "Credly Badges",
    description: "Fetch earned Credly badges for the current student",
    endpoint: { method: "GET", path: "/api/credly/badges" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["certifications", "credly", "integration"],
  },
  {
    id: "certifications.credentials_share",
    namespace: "certifications",
    name: "Share Credentials",
    description: "Generate or retrieve shareable credential links",
    endpoint: { method: "GET", path: "/api/credentials/share" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["certifications", "sharing"],
  },
  {
    id: "certifications.credentials_create",
    namespace: "certifications",
    name: "Create Credential Share",
    description: "Create a new shareable credential link",
    endpoint: { method: "POST", path: "/api/credentials/share" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["certifications", "sharing"],
  },

  // ─── Portfolio Namespace ─────────────────────────────────────────────────────

  {
    id: "portfolio.list",
    namespace: "portfolio",
    name: "List Portfolio Items",
    description: "Retrieve all portfolio entries for the current student",
    endpoint: { method: "GET", path: "/api/portfolio" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["portfolio", "core"],
  },
  {
    id: "portfolio.create",
    namespace: "portfolio",
    name: "Create Portfolio Item",
    description: "Add a new item to the student portfolio",
    endpoint: { method: "POST", path: "/api/portfolio" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "core"],
  },
  {
    id: "portfolio.update",
    namespace: "portfolio",
    name: "Update Portfolio Item",
    description: "Edit an existing portfolio entry",
    endpoint: { method: "PUT", path: "/api/portfolio" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "core"],
  },
  {
    id: "portfolio.delete",
    namespace: "portfolio",
    name: "Delete Portfolio Item",
    description: "Remove a portfolio entry",
    endpoint: { method: "DELETE", path: "/api/portfolio" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "core"],
  },
  {
    id: "portfolio.resume_get",
    namespace: "portfolio",
    name: "Get Resume Data",
    description: "Retrieve stored resume data for the current student",
    endpoint: { method: "GET", path: "/api/resume" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["portfolio", "resume"],
  },
  {
    id: "portfolio.resume_save",
    namespace: "portfolio",
    name: "Save Resume Data",
    description: "Save or update resume structured data",
    endpoint: { method: "POST", path: "/api/resume" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "resume"],
  },
  {
    id: "portfolio.resume_application_file",
    namespace: "portfolio",
    name: "Generate Application File",
    description: "Generate a downloadable resume file for job applications",
    endpoint: { method: "POST", path: "/api/resume/application-file" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    rateLimit: { maxPerHour: 10 },
    enabled: true,
    tags: ["portfolio", "resume", "export"],
  },
  {
    id: "portfolio.vision_board_list",
    namespace: "portfolio",
    name: "Vision Board Items",
    description: "Retrieve vision board items for the current student",
    endpoint: { method: "GET", path: "/api/vision-board" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["portfolio", "vision-board"],
  },
  {
    id: "portfolio.vision_board_create",
    namespace: "portfolio",
    name: "Create Vision Board Item",
    description: "Add a new vision board entry (image, text, goal)",
    endpoint: { method: "POST", path: "/api/vision-board" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "vision-board"],
  },
  {
    id: "portfolio.vision_board_update",
    namespace: "portfolio",
    name: "Update Vision Board Item",
    description: "Edit an existing vision board entry",
    endpoint: { method: "PUT", path: "/api/vision-board" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "vision-board"],
  },
  {
    id: "portfolio.vision_board_delete",
    namespace: "portfolio",
    name: "Delete Vision Board Item",
    description: "Remove a vision board entry",
    endpoint: { method: "DELETE", path: "/api/vision-board" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "vision-board"],
  },
  {
    id: "portfolio.documents_list",
    namespace: "portfolio",
    name: "List Documents",
    description: "Retrieve uploaded documents for the current student",
    endpoint: { method: "GET", path: "/api/documents" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["portfolio", "documents"],
  },
  {
    id: "portfolio.documents_download",
    namespace: "portfolio",
    name: "Download Document",
    description: "Download a previously uploaded document",
    endpoint: { method: "GET", path: "/api/documents/download" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["portfolio", "documents"],
  },

  // ─── Career Namespace ────────────────────────────────────────────────────────

  {
    id: "career.opportunities",
    namespace: "career",
    name: "List Opportunities",
    description: "Browse career and training opportunities",
    endpoint: { method: "GET", path: "/api/opportunities" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "opportunities"],
  },
  {
    id: "career.events",
    namespace: "career",
    name: "List Events",
    description: "Browse upcoming career events, workshops, and job fairs",
    endpoint: { method: "GET", path: "/api/events" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "events"],
  },
  {
    id: "career.events_register",
    namespace: "career",
    name: "Register for Event",
    description: "Register the student for a career event",
    endpoint: { method: "POST", path: "/api/events/:id/register" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "events"],
  },
  {
    id: "career.events_unregister",
    namespace: "career",
    name: "Unregister from Event",
    description: "Cancel event registration",
    endpoint: { method: "DELETE", path: "/api/events/:id/register" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "events"],
  },
  {
    id: "career.apply",
    namespace: "career",
    name: "Apply to Opportunity",
    description: "Submit an application for a career opportunity",
    endpoint: { method: "POST", path: "/api/applications" },
    requiredRoles: ["student"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "applications"],
  },
  {
    id: "career.jobs",
    namespace: "career",
    name: "Search Jobs",
    description: "Search aggregated job listings from external boards",
    endpoint: { method: "GET", path: "/api/jobs" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "jobs"],
  },
  {
    id: "career.jobs_save",
    namespace: "career",
    name: "Save Job",
    description: "Bookmark a job listing for later review",
    endpoint: { method: "POST", path: "/api/jobs/save" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "jobs"],
  },
  {
    id: "career.opportunities_manage",
    namespace: "career",
    name: "Manage Opportunities",
    description: "Teacher CRUD for career opportunities",
    endpoint: { method: "GET", path: "/api/teacher/opportunities" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "config"],
  },
  {
    id: "career.opportunities_create",
    namespace: "career",
    name: "Create Opportunity",
    description: "Teacher creates a new career opportunity listing",
    endpoint: { method: "POST", path: "/api/teacher/opportunities" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "teacher", "config"],
  },
  {
    id: "career.opportunities_update",
    namespace: "career",
    name: "Update Opportunity",
    description: "Teacher edits an existing opportunity listing",
    endpoint: { method: "PUT", path: "/api/teacher/opportunities" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "config"],
  },
  {
    id: "career.opportunities_delete",
    namespace: "career",
    name: "Delete Opportunity",
    description: "Teacher removes an opportunity listing",
    endpoint: { method: "DELETE", path: "/api/teacher/opportunities" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "config"],
  },
  {
    id: "career.events_manage",
    namespace: "career",
    name: "Manage Events",
    description: "Teacher lists all career events",
    endpoint: { method: "GET", path: "/api/teacher/events" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "teacher", "events"],
  },
  {
    id: "career.events_create",
    namespace: "career",
    name: "Create Event",
    description: "Teacher creates a new career event",
    endpoint: { method: "POST", path: "/api/teacher/events" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "teacher", "events"],
  },
  {
    id: "career.events_update",
    namespace: "career",
    name: "Update Event",
    description: "Teacher edits an existing career event",
    endpoint: { method: "PUT", path: "/api/teacher/events" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "events"],
  },
  {
    id: "career.events_delete",
    namespace: "career",
    name: "Delete Event",
    description: "Teacher removes a career event",
    endpoint: { method: "DELETE", path: "/api/teacher/events" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "events"],
  },
  {
    id: "career.jobs_config",
    namespace: "career",
    name: "Job Board Config",
    description: "View or update job board scraping configuration",
    endpoint: { method: "GET", path: "/api/teacher/jobs/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "config", "jobs"],
  },
  {
    id: "career.jobs_config_update",
    namespace: "career",
    name: "Update Job Board Config",
    description: "Modify job board scraping keywords and sources",
    endpoint: { method: "PUT", path: "/api/teacher/jobs/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "teacher", "config", "jobs"],
  },
  {
    id: "career.jobs_refresh",
    namespace: "career",
    name: "Refresh Job Listings",
    description: "Trigger a manual refresh of job board data",
    endpoint: { method: "POST", path: "/api/teacher/jobs/refresh" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    rateLimit: { maxPerHour: 3 },
    enabled: true,
    tags: ["career", "teacher", "jobs"],
  },
  {
    id: "career.pathways_list",
    namespace: "career",
    name: "List Pathways",
    description: "View all defined career pathways",
    endpoint: { method: "GET", path: "/api/teacher/pathways" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "teacher", "pathways"],
  },
  {
    id: "career.pathways_create",
    namespace: "career",
    name: "Create Pathway",
    description: "Define a new career pathway with milestones",
    endpoint: { method: "POST", path: "/api/teacher/pathways" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "teacher", "pathways"],
  },
  {
    id: "career.pathways_get",
    namespace: "career",
    name: "Get Pathway Detail",
    description: "Retrieve a single pathway with full milestone detail",
    endpoint: { method: "GET", path: "/api/teacher/pathways/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["career", "teacher", "pathways"],
  },
  {
    id: "career.pathways_update",
    namespace: "career",
    name: "Update Pathway",
    description: "Edit an existing career pathway",
    endpoint: { method: "PATCH", path: "/api/teacher/pathways/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["career", "teacher", "pathways"],
  },
  {
    id: "career.pathways_delete",
    namespace: "career",
    name: "Delete Pathway",
    description: "Remove a career pathway definition",
    endpoint: { method: "DELETE", path: "/api/teacher/pathways/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["career", "teacher", "pathways"],
  },

  // ─── Advising Namespace ──────────────────────────────────────────────────────

  {
    id: "advising.availability",
    namespace: "advising",
    name: "View Availability",
    description: "Retrieve available advising appointment slots",
    endpoint: { method: "GET", path: "/api/appointments/availability" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["advising", "scheduling"],
  },
  {
    id: "advising.book",
    namespace: "advising",
    name: "Book Appointment",
    description: "Schedule an advising appointment with an available slot",
    endpoint: { method: "POST", path: "/api/appointments/book" },
    requiredRoles: ["student"],
    auditLevel: "full",
    rateLimit: { maxPerDay: 3 },
    enabled: true,
    tags: ["advising", "scheduling"],
  },
  {
    id: "advising.teacher_availability_list",
    namespace: "advising",
    name: "Teacher Availability List",
    description: "Teacher views their own availability schedule",
    endpoint: { method: "GET", path: "/api/teacher/availability" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["advising", "teacher", "scheduling"],
  },
  {
    id: "advising.teacher_availability_create",
    namespace: "advising",
    name: "Create Availability Slot",
    description: "Teacher adds a new availability slot for appointments",
    endpoint: { method: "POST", path: "/api/teacher/availability" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "teacher", "scheduling"],
  },
  {
    id: "advising.teacher_availability_delete",
    namespace: "advising",
    name: "Delete Availability Slot",
    description: "Teacher removes an availability slot",
    endpoint: { method: "DELETE", path: "/api/teacher/availability/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "teacher", "scheduling"],
  },
  {
    id: "advising.appointment_update",
    namespace: "advising",
    name: "Update Appointment",
    description: "Teacher updates appointment status (confirm, cancel, complete)",
    endpoint: { method: "PATCH", path: "/api/teacher/appointments/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["advising", "teacher"],
  },
  {
    id: "advising.appointment_reminders",
    namespace: "advising",
    name: "Send Appointment Reminders",
    description: "Trigger appointment reminder notifications",
    endpoint: { method: "POST", path: "/api/teacher/appointments/reminders" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "teacher", "notifications"],
  },
  {
    id: "advising.student_appointments",
    namespace: "advising",
    name: "Student Appointments",
    description: "Teacher views appointment history for a specific student",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/appointments" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "teacher"],
  },
  {
    id: "advising.tasks_update",
    namespace: "advising",
    name: "Update Task",
    description: "Update an advising task status",
    endpoint: { method: "PATCH", path: "/api/tasks/:id" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "tasks"],
  },
  {
    id: "advising.student_tasks",
    namespace: "advising",
    name: "Assign Student Task",
    description: "Teacher assigns a task to a specific student",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/tasks" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["advising", "teacher", "tasks"],
  },
  {
    id: "advising.alerts_update",
    namespace: "advising",
    name: "Update Alert",
    description: "Teacher acknowledges or dismisses a student alert",
    endpoint: { method: "PATCH", path: "/api/teacher/alerts/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["advising", "teacher", "alerts"],
  },

  // ─── Files Namespace ─────────────────────────────────────────────────────────

  {
    id: "files.list",
    namespace: "files",
    name: "List Files",
    description: "List uploaded files for the current student",
    endpoint: { method: "GET", path: "/api/files" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["files"],
  },
  {
    id: "files.upload",
    namespace: "files",
    name: "Upload File",
    description: "Upload a file to student storage (local or Supabase)",
    endpoint: { method: "POST", path: "/api/files" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    rateLimit: { maxPerHour: 20, maxPerDay: 50 },
    enabled: true,
    tags: ["files", "storage"],
  },
  {
    id: "files.download",
    namespace: "files",
    name: "Download File",
    description: "Download a previously uploaded file",
    endpoint: { method: "GET", path: "/api/files/download" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["files", "storage"],
  },
  {
    id: "files.delete",
    namespace: "files",
    name: "Delete File",
    description: "Remove a file from student storage",
    endpoint: { method: "DELETE", path: "/api/files" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["files", "storage"],
  },
  {
    id: "files.forms_upload",
    namespace: "files",
    name: "Upload Form",
    description: "Upload a signed form document",
    endpoint: { method: "POST", path: "/api/forms/upload" },
    requiredRoles: ["student"],
    auditLevel: "full",
    enabled: true,
    tags: ["files", "forms", "compliance"],
  },
  {
    id: "files.forms_sign",
    namespace: "files",
    name: "Sign Form",
    description: "Apply an electronic signature to a form",
    endpoint: { method: "POST", path: "/api/forms/sign" },
    requiredRoles: ["student"],
    auditLevel: "full",
    enabled: true,
    tags: ["files", "forms", "compliance"],
  },
  {
    id: "files.forms_status",
    namespace: "files",
    name: "Form Status",
    description: "Check the completion status of required forms",
    endpoint: { method: "GET", path: "/api/forms/status" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["files", "forms"],
  },
  {
    id: "files.forms_download",
    namespace: "files",
    name: "Download Form Template",
    description: "Download a blank or pre-filled form template",
    endpoint: { method: "GET", path: "/api/forms/download" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["files", "forms"],
  },

  // ─── Learning Namespace ──────────────────────────────────────────────────────

  {
    id: "learning.platforms",
    namespace: "learning",
    name: "List LMS Platforms",
    description: "Retrieve available learning management system platforms",
    endpoint: { method: "GET", path: "/api/lms/platforms" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["learning", "lms"],
  },
  {
    id: "learning.visit_track",
    namespace: "learning",
    name: "Track LMS Visit",
    description: "Record that a student visited an LMS platform link",
    endpoint: { method: "POST", path: "/api/lms/platforms/visit" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["learning", "lms", "tracking"],
  },
  {
    id: "learning.lms_list",
    namespace: "learning",
    name: "LMS Overview",
    description: "Get overall LMS enrollment and progress data",
    endpoint: { method: "GET", path: "/api/lms" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["learning", "lms"],
  },
  {
    id: "learning.teacher_lms_list",
    namespace: "learning",
    name: "Teacher LMS Management",
    description: "Teacher view of all LMS platform configurations",
    endpoint: { method: "GET", path: "/api/teacher/lms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["learning", "teacher", "lms"],
  },
  {
    id: "learning.teacher_lms_create",
    namespace: "learning",
    name: "Create LMS Platform",
    description: "Teacher adds a new LMS platform link",
    endpoint: { method: "POST", path: "/api/teacher/lms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["learning", "teacher", "lms", "config"],
  },
  {
    id: "learning.teacher_lms_update",
    namespace: "learning",
    name: "Update LMS Platform",
    description: "Teacher edits an existing LMS platform entry",
    endpoint: { method: "PUT", path: "/api/teacher/lms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["learning", "teacher", "lms", "config"],
  },
  {
    id: "learning.teacher_lms_delete",
    namespace: "learning",
    name: "Delete LMS Platform",
    description: "Teacher removes an LMS platform",
    endpoint: { method: "DELETE", path: "/api/teacher/lms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["learning", "teacher", "lms", "config"],
  },
  {
    id: "learning.class_progress",
    namespace: "learning",
    name: "Class Progress",
    description: "Student views their class-level progress data",
    endpoint: { method: "GET", path: "/api/class/progress" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["learning", "progress"],
  },
  {
    id: "learning.mood",
    namespace: "learning",
    name: "Mood History",
    description: "Retrieve mood tracking history for the current student",
    endpoint: { method: "GET", path: "/api/mood" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["learning", "wellness"],
  },

  // ─── Notifications Namespace ─────────────────────────────────────────────────

  {
    id: "notifications.list",
    namespace: "notifications",
    name: "List Notifications",
    description: "Retrieve notifications for the current user",
    endpoint: { method: "GET", path: "/api/notifications" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["notifications"],
  },
  {
    id: "notifications.mark_read",
    namespace: "notifications",
    name: "Mark Notification Read",
    description: "Mark one or more notifications as read",
    endpoint: { method: "POST", path: "/api/notifications" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["notifications"],
  },
  {
    id: "notifications.stream",
    namespace: "notifications",
    name: "Notification Stream",
    description: "Server-Sent Events stream for real-time notifications",
    endpoint: { method: "GET", path: "/api/notifications/stream" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["notifications", "realtime"],
  },
  {
    id: "notifications.preferences_get",
    namespace: "notifications",
    name: "Get Notification Preferences",
    description: "Retrieve notification preference settings",
    endpoint: { method: "GET", path: "/api/notifications/preferences" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["notifications", "settings"],
  },
  {
    id: "notifications.preferences_update",
    namespace: "notifications",
    name: "Update Notification Preferences",
    description: "Modify notification preference settings",
    endpoint: { method: "PUT", path: "/api/notifications/preferences" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["notifications", "settings"],
  },

  // ─── Progression Namespace ───────────────────────────────────────────────────

  {
    id: "progression.state",
    namespace: "progression",
    name: "Progression State",
    description: "Get the current student progression level and badge status",
    endpoint: { method: "GET", path: "/api/progression" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["progression", "gamification"],
  },
  {
    id: "progression.activity_log",
    namespace: "progression",
    name: "Activity Log",
    description: "Retrieve the student activity log for progression tracking",
    endpoint: { method: "GET", path: "/api/progression/activity" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["progression", "tracking"],
  },

  // ─── Classes Namespace ───────────────────────────────────────────────────────

  {
    id: "classes.list",
    namespace: "classes",
    name: "List Classes",
    description: "Teacher lists all SPOKES classes they manage",
    endpoint: { method: "GET", path: "/api/teacher/classes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher"],
  },
  {
    id: "classes.create",
    namespace: "classes",
    name: "Create Class",
    description: "Teacher creates a new SPOKES class section",
    endpoint: { method: "POST", path: "/api/teacher/classes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher"],
  },
  {
    id: "classes.get",
    namespace: "classes",
    name: "Get Class Detail",
    description: "Retrieve detailed info about a specific class",
    endpoint: { method: "GET", path: "/api/teacher/classes/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher"],
  },
  {
    id: "classes.update",
    namespace: "classes",
    name: "Update Class",
    description: "Teacher updates class metadata (name, dates, etc.)",
    endpoint: { method: "PATCH", path: "/api/teacher/classes/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher"],
  },
  {
    id: "classes.roster",
    namespace: "classes",
    name: "Class Roster",
    description: "View all students enrolled in a class",
    endpoint: { method: "POST", path: "/api/teacher/classes/:id/students" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher", "roster"],
  },
  {
    id: "classes.enroll",
    namespace: "classes",
    name: "Enroll Student",
    description: "Enroll a student in a class section",
    endpoint: { method: "POST", path: "/api/teacher/classes/:id/students" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher", "enrollment"],
  },
  {
    id: "classes.enrollment_update",
    namespace: "classes",
    name: "Update Enrollment",
    description: "Update a student enrollment status (active, withdrawn, etc.)",
    endpoint: { method: "PATCH", path: "/api/teacher/classes/:id/enrollments/:enrollmentId" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher", "enrollment"],
  },
  {
    id: "classes.requirements_list",
    namespace: "classes",
    name: "List Class Requirements",
    description: "View all requirements defined for a class",
    endpoint: { method: "GET", path: "/api/teacher/classes/:id/requirements" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher", "requirements"],
  },
  {
    id: "classes.requirements_create",
    namespace: "classes",
    name: "Create Class Requirement",
    description: "Add a new requirement to a class",
    endpoint: { method: "POST", path: "/api/teacher/classes/:id/requirements" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher", "requirements"],
  },
  {
    id: "classes.requirements_update",
    namespace: "classes",
    name: "Update Class Requirement",
    description: "Modify an existing class requirement",
    endpoint: { method: "PUT", path: "/api/teacher/classes/:id/requirements" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["classes", "teacher", "requirements"],
  },
  {
    id: "classes.requirements_delete",
    namespace: "classes",
    name: "Delete Class Requirement",
    description: "Remove a class requirement",
    endpoint: { method: "DELETE", path: "/api/teacher/classes/:id/requirements" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["classes", "teacher", "requirements"],
  },
  {
    id: "classes.welcome_letter_get",
    namespace: "classes",
    name: "Get Welcome Letter",
    description: "Retrieve the current class welcome letter template",
    endpoint: { method: "GET", path: "/api/teacher/welcome-letter" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher", "onboarding"],
  },
  {
    id: "classes.welcome_letter_update",
    namespace: "classes",
    name: "Update Welcome Letter",
    description: "Create or update the welcome letter template",
    endpoint: { method: "POST", path: "/api/teacher/welcome-letter" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["classes", "teacher", "onboarding"],
  },
  {
    id: "classes.welcome_letter_delete",
    namespace: "classes",
    name: "Delete Welcome Letter",
    description: "Remove the welcome letter template",
    endpoint: { method: "DELETE", path: "/api/teacher/welcome-letter" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["classes", "teacher", "onboarding"],
  },
  {
    id: "classes.dashboard",
    namespace: "classes",
    name: "Teacher Dashboard",
    description: "Aggregated dashboard data for the teacher overview",
    endpoint: { method: "GET", path: "/api/teacher/dashboard" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["classes", "teacher", "dashboard"],
  },

  // ─── Reports Namespace (teacher/admin) ───────────────────────────────────────

  {
    id: "reports.academic_kpi",
    namespace: "reports",
    name: "Academic KPI Report",
    description: "Academic performance KPIs across students and classes",
    endpoint: { method: "GET", path: "/api/teacher/reports/academic-kpi" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "kpi", "academic"],
  },
  {
    id: "reports.grant_kpi",
    namespace: "reports",
    name: "Grant KPI Report",
    description: "Grant-related performance KPIs for SPOKES funding compliance",
    endpoint: { method: "GET", path: "/api/teacher/reports/grant-kpi" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["reports", "kpi", "grant", "compliance"],
  },
  {
    id: "reports.grant_kpi_history",
    namespace: "reports",
    name: "Grant KPI History",
    description: "Historical grant KPI trends over time",
    endpoint: { method: "GET", path: "/api/teacher/reports/grant-kpi/history" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "kpi", "grant", "history"],
  },
  {
    id: "reports.grant_kpi_students",
    namespace: "reports",
    name: "Grant KPI Student Detail",
    description: "Per-student detail for grant KPI metrics",
    endpoint: { method: "GET", path: "/api/teacher/reports/grant-kpi/students" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["reports", "kpi", "grant", "pii"],
  },
  {
    id: "reports.outcomes",
    namespace: "reports",
    name: "Outcomes Report",
    description: "Student outcomes data (employment, credentials, completion)",
    endpoint: { method: "GET", path: "/api/teacher/reports/outcomes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "outcomes"],
  },
  {
    id: "reports.readiness",
    namespace: "reports",
    name: "Readiness Report",
    description: "Monthly career-readiness scores for all students",
    endpoint: { method: "GET", path: "/api/teacher/reports/readiness-monthly" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "readiness"],
  },
  {
    id: "reports.spokes",
    namespace: "reports",
    name: "SPOKES Report",
    description: "Aggregate SPOKES module completion and attendance data",
    endpoint: { method: "GET", path: "/api/teacher/reports/spokes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "spokes"],
  },
  {
    id: "reports.intervention_queue",
    namespace: "reports",
    name: "Intervention Queue",
    description: "Priority-ranked list of students needing teacher intervention",
    endpoint: { method: "GET", path: "/api/teacher/intervention-queue" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["reports", "intervention", "priority"],
  },

  // ─── Admin Namespace ─────────────────────────────────────────────────────────

  {
    id: "admin.audit_trail",
    namespace: "admin",
    name: "Audit Trail",
    description: "View the full audit log of all system actions",
    endpoint: { method: "GET", path: "/api/teacher/audit" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "audit", "compliance"],
  },
  {
    id: "admin.student_detail",
    namespace: "admin",
    name: "Student Detail",
    description: "View comprehensive student profile data",
    endpoint: { method: "GET", path: "/api/teacher/students/:id" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    requiresContext: ["studentProfile"],
    tags: ["admin", "teacher", "pii"],
  },
  {
    id: "admin.student_status_update",
    namespace: "admin",
    name: "Update Student Status",
    description: "Change a student account status (active, inactive, suspended)",
    endpoint: { method: "PATCH", path: "/api/teacher/students/:id/status" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "pii"],
  },
  {
    id: "admin.student_archive",
    namespace: "admin",
    name: "Archive Student",
    description: "Archive a student record and related data",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/archive" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "pii", "data-lifecycle"],
  },
  {
    id: "admin.student_archive_check",
    namespace: "admin",
    name: "Check Archive Status",
    description: "Verify whether a student has been archived",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/archive" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "teacher"],
  },
  {
    id: "admin.student_export",
    namespace: "admin",
    name: "Student Data Export",
    description: "Export student data in CSV/JSON for grant reporting",
    endpoint: { method: "GET", path: "/api/teacher/export" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "export", "pii", "compliance"],
  },
  {
    id: "admin.student_usage",
    namespace: "admin",
    name: "Student AI Usage",
    description: "View AI token usage stats for a specific student",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/usage" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "teacher", "ai", "usage"],
  },
  {
    id: "admin.student_mood",
    namespace: "admin",
    name: "Student Mood History",
    description: "Teacher views mood tracking history for a student",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/mood" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "wellness", "pii"],
  },
  {
    id: "admin.student_notes_list",
    namespace: "admin",
    name: "Student Notes",
    description: "View advisor notes for a specific student",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/notes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "notes", "pii"],
  },
  {
    id: "admin.student_notes_create",
    namespace: "admin",
    name: "Create Student Note",
    description: "Add an advisor note about a student",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/notes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "notes", "pii"],
  },
  {
    id: "admin.student_notes_update",
    namespace: "admin",
    name: "Update Student Note",
    description: "Edit an existing advisor note",
    endpoint: { method: "PATCH", path: "/api/teacher/students/:id/notes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "notes", "pii"],
  },
  {
    id: "admin.student_notes_delete",
    namespace: "admin",
    name: "Delete Student Note",
    description: "Remove an advisor note",
    endpoint: { method: "DELETE", path: "/api/teacher/students/:id/notes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "notes", "pii"],
  },
  {
    id: "admin.student_reset_password",
    namespace: "admin",
    name: "Reset Student Password",
    description: "Teacher resets a student password on their behalf",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/reset-password" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "security"],
  },
  {
    id: "admin.student_forms",
    namespace: "admin",
    name: "Student Forms",
    description: "Teacher views form completion status for a student",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/forms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "teacher", "forms"],
  },
  {
    id: "admin.student_forms_update",
    namespace: "admin",
    name: "Update Student Form Status",
    description: "Teacher updates form review status for a student",
    endpoint: { method: "PATCH", path: "/api/teacher/students/:id/forms" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "teacher", "forms", "compliance"],
  },
  {
    id: "admin.webhooks_list",
    namespace: "admin",
    name: "List Webhooks",
    description: "View all configured webhook subscriptions",
    endpoint: { method: "GET", path: "/api/admin/webhooks" },
    requiredRoles: ["admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "webhooks", "integration"],
  },
  {
    id: "admin.webhooks_create",
    namespace: "admin",
    name: "Create Webhook",
    description: "Register a new webhook subscription",
    endpoint: { method: "POST", path: "/api/admin/webhooks" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "webhooks", "integration"],
  },
  {
    id: "admin.webhooks_update",
    namespace: "admin",
    name: "Update Webhook",
    description: "Modify an existing webhook subscription",
    endpoint: { method: "PATCH", path: "/api/admin/webhooks" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "webhooks", "integration"],
  },
  {
    id: "admin.webhooks_delete",
    namespace: "admin",
    name: "Delete Webhook",
    description: "Remove a webhook subscription",
    endpoint: { method: "DELETE", path: "/api/admin/webhooks" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "webhooks", "integration"],
  },
  {
    id: "admin.ai_config_get",
    namespace: "admin",
    name: "Get AI Config",
    description: "View current AI model configuration and API key status",
    endpoint: { method: "GET", path: "/api/admin/ai-config" },
    requiredRoles: ["admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "ai", "config"],
  },
  {
    id: "admin.ai_config_update",
    namespace: "admin",
    name: "Update AI Config",
    description: "Modify AI model settings (model name, temperature, etc.)",
    endpoint: { method: "PUT", path: "/api/admin/ai-config" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "ai", "config"],
  },
  {
    id: "admin.ai_config_delete",
    namespace: "admin",
    name: "Delete AI Config Override",
    description: "Remove custom AI config and revert to defaults",
    endpoint: { method: "DELETE", path: "/api/admin/ai-config" },
    requiredRoles: ["admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "ai", "config"],
  },
  {
    id: "admin.ai_config_test",
    namespace: "admin",
    name: "Test AI Config",
    description: "Send a test prompt to verify AI configuration works",
    endpoint: { method: "POST", path: "/api/admin/ai-config/test" },
    requiredRoles: ["admin"],
    tokenBudget: 500,
    auditLevel: "basic",
    rateLimit: { maxPerHour: 10 },
    enabled: true,
    tags: ["admin", "ai", "config", "test"],
  },
  {
    id: "admin.settings_api_key_get",
    namespace: "admin",
    name: "Get API Key Status",
    description: "Check whether a personal API key is configured",
    endpoint: { method: "GET", path: "/api/settings/api-key" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["admin", "settings", "api-key"],
  },
  {
    id: "admin.settings_api_key_set",
    namespace: "admin",
    name: "Set API Key",
    description: "Store a personal Gemini API key for enhanced AI access",
    endpoint: { method: "POST", path: "/api/settings/api-key" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "settings", "api-key", "security"],
  },
  {
    id: "admin.settings_api_key_delete",
    namespace: "admin",
    name: "Delete API Key",
    description: "Remove a stored personal API key",
    endpoint: { method: "DELETE", path: "/api/settings/api-key" },
    requiredRoles: ["student", "teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["admin", "settings", "api-key", "security"],
  },
  {
    id: "admin.settings_credly_get",
    namespace: "admin",
    name: "Get Credly Settings",
    description: "View Credly integration configuration",
    endpoint: { method: "GET", path: "/api/settings/credly" },
    requiredRoles: ["student"],
    auditLevel: "none",
    enabled: true,
    tags: ["admin", "settings", "credly"],
  },
  {
    id: "admin.settings_credly_set",
    namespace: "admin",
    name: "Set Credly Username",
    description: "Configure Credly username for badge syncing",
    endpoint: { method: "POST", path: "/api/settings/credly" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "settings", "credly"],
  },
  {
    id: "admin.settings_credly_delete",
    namespace: "admin",
    name: "Delete Credly Settings",
    description: "Remove Credly integration configuration",
    endpoint: { method: "DELETE", path: "/api/settings/credly" },
    requiredRoles: ["student"],
    auditLevel: "basic",
    enabled: true,
    tags: ["admin", "settings", "credly"],
  },

  // ─── SPOKES Namespace ────────────────────────────────────────────────────────

  {
    id: "spokes.record",
    namespace: "spokes",
    name: "Student SPOKES Record",
    description: "View SPOKES module progress and attendance for a student",
    endpoint: { method: "GET", path: "/api/teacher/students/:id/spokes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["spokes", "teacher"],
  },
  {
    id: "spokes.record_update",
    namespace: "spokes",
    name: "Update SPOKES Record",
    description: "Update a student SPOKES attendance or module status",
    endpoint: { method: "PUT", path: "/api/teacher/students/:id/spokes" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher"],
  },
  {
    id: "spokes.checklist",
    namespace: "spokes",
    name: "SPOKES Checklist",
    description: "Update module checklist completion for a student",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/spokes/checklist" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["spokes", "teacher", "checklist"],
  },
  {
    id: "spokes.modules_complete",
    namespace: "spokes",
    name: "Complete SPOKES Module",
    description: "Mark a SPOKES module as completed for a student",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/spokes/modules" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "modules"],
  },
  {
    id: "spokes.modules_reopen",
    namespace: "spokes",
    name: "Reopen SPOKES Module",
    description: "Revert a completed SPOKES module to in-progress",
    endpoint: { method: "DELETE", path: "/api/teacher/students/:id/spokes/modules" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "modules"],
  },
  {
    id: "spokes.follow_up_create",
    namespace: "spokes",
    name: "Create Follow-Up",
    description: "Schedule a follow-up action for a student SPOKES module",
    endpoint: { method: "POST", path: "/api/teacher/students/:id/spokes/follow-up" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["spokes", "teacher", "follow-up"],
  },
  {
    id: "spokes.follow_up_delete",
    namespace: "spokes",
    name: "Delete Follow-Up",
    description: "Remove a scheduled SPOKES follow-up action",
    endpoint: { method: "DELETE", path: "/api/teacher/students/:id/spokes/follow-up" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["spokes", "teacher", "follow-up"],
  },
  {
    id: "spokes.config_list",
    namespace: "spokes",
    name: "SPOKES Config",
    description: "View SPOKES module configuration and templates",
    endpoint: { method: "GET", path: "/api/teacher/spokes/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "none",
    enabled: true,
    tags: ["spokes", "teacher", "config"],
  },
  {
    id: "spokes.config_create",
    namespace: "spokes",
    name: "Create SPOKES Config",
    description: "Add a new SPOKES module configuration",
    endpoint: { method: "POST", path: "/api/teacher/spokes/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "config"],
  },
  {
    id: "spokes.config_update",
    namespace: "spokes",
    name: "Update SPOKES Config",
    description: "Modify an existing SPOKES module configuration",
    endpoint: { method: "PUT", path: "/api/teacher/spokes/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "config"],
  },
  {
    id: "spokes.config_delete",
    namespace: "spokes",
    name: "Delete SPOKES Config",
    description: "Remove a SPOKES module configuration",
    endpoint: { method: "DELETE", path: "/api/teacher/spokes/config" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "config"],
  },
  {
    id: "spokes.referrals_list",
    namespace: "spokes",
    name: "List Referrals",
    description: "View SPOKES referrals and external service connections",
    endpoint: { method: "GET", path: "/api/teacher/spokes/referrals" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "basic",
    enabled: true,
    tags: ["spokes", "teacher", "referrals"],
  },
  {
    id: "spokes.referrals_create",
    namespace: "spokes",
    name: "Create Referral",
    description: "Create a new SPOKES external service referral",
    endpoint: { method: "POST", path: "/api/teacher/spokes/referrals" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "referrals"],
  },
  {
    id: "spokes.referrals_delete",
    namespace: "spokes",
    name: "Delete Referral",
    description: "Remove a SPOKES referral record",
    endpoint: { method: "DELETE", path: "/api/teacher/spokes/referrals" },
    requiredRoles: ["teacher", "admin"],
    auditLevel: "full",
    enabled: true,
    tags: ["spokes", "teacher", "referrals"],
  },
] as const;
