-- No-op: deduplicated migration.
--
-- This migration was committed accidentally in the same commit (3ea9d5c) as
-- `20260331000000_add_job_board_models`, with byte-identical SQL. On a fresh
-- database, `20260331000000` creates JobClassConfig / JobListing / StudentSavedJob
-- (plus indexes and FKs), so re-running those CREATE statements here failed with
-- `42P07 relation "JobClassConfig" already exists` — which broke `prisma migrate
-- deploy` against any clean database (CI's RLS test DB, and disaster-recovery /
-- new-environment provisioning).
--
-- Production already has this migration recorded as applied (it was manually
-- resolved when the duplicate first failed on deploy), so `migrate deploy` skips
-- it there and is unaffected by emptying it. Reducing it to a no-op makes the
-- migration history clean-DB reproducible again. The objects it used to create
-- live in `20260331000000_add_job_board_models`.
