-- Phase 1 — Seed "coordinator" and "cdc" system roles
-- Permission wiring happens in Phase 5; Phase 1 only creates the role rows
-- so Student.role can be set to either value without breaking existing checks.
--
-- Hierarchy levels (lower = more trust):
--   1 = admin
--   2 = coordinator (regional oversight)
--   3 = teacher | cdc (classroom-facing; different scopes)
--   4 = student
--
-- IDs are static sentinel values (sys_*_role_v1) so the rows can be referenced
-- deterministically across environments and are easy to spot in logs. They do
-- not collide with cuid() values generated by Prisma client.

INSERT INTO "visionquest"."Role"
  ("id", "name", "displayName", "hierarchyLevel", "description", "isSystem", "createdAt")
VALUES
  (
    'sys_coordinator_role_v1',
    'coordinator',
    'Regional Coordinator',
    2,
    'Oversees classrooms in a region; manages budget, grant reporting, and program administration.',
    true,
    NOW()
  ),
  (
    'sys_cdc_role_v1',
    'cdc',
    'Career Development Consultant',
    3,
    'Rotates between classrooms; supports job readiness, resumes, interview prep, and community needs.',
    true,
    NOW()
  )
ON CONFLICT ("name") DO NOTHING;
