#!/usr/bin/env bash
# Cloud Agent install phase for VisionQuest.
#
# Idempotent, one-time repository bootstrap that runs after the source is
# checked out. It provisions a local PostgreSQL 16 + pgvector instance,
# generates a local .env.local (only when absent), installs Node
# dependencies, and applies Prisma migrations + idempotent seed data.
#
# Per-boot service startup lives in .cursor/start.sh — do NOT start
# long-running processes here.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
DB_NAME=visionquest
DB_USER=postgres
DB_PASS=postgres

echo "==> [install] Ensuring PostgreSQL ${PG_VERSION} + pgvector are installed"
if ! dpkg -s "postgresql-${PG_VERSION}" >/dev/null 2>&1 \
  || ! dpkg -s "postgresql-${PG_VERSION}-pgvector" >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo apt-get install -y \
    "postgresql-${PG_VERSION}" \
    "postgresql-${PG_VERSION}-pgvector" \
    postgresql-contrib
fi

echo "==> [install] Starting the PostgreSQL cluster"
if ! sudo pg_lsclusters -h | awk '{print $4}' | grep -q '^online$'; then
  sudo pg_ctlcluster "${PG_VERSION}" main start || true
fi

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> [install] Configuring the ${DB_NAME} database, role password, and pgvector"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c \
  "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASS}';"
if ! sudo -u postgres psql -tAc \
  "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" | grep -q 1; then
  sudo -u postgres createdb "${DB_NAME}"
fi
# pgvector must live on the default search_path (public) so the multiSchema
# "visionquest" tables can reference the vector type during migrations.
sudo -u postgres psql -d "${DB_NAME}" -v ON_ERROR_STOP=1 -c \
  "CREATE EXTENSION IF NOT EXISTS vector;"

echo "==> [install] Ensuring .env.local exists"
if [ ! -f .env.local ]; then
  JWT_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
  API_KEY_ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\n')"
  TEACHER_KEY="$(openssl rand -base64 32 | tr -d '\n')"
  ADMIN_KEY="$(openssl rand -base64 32 | tr -d '\n')"
  CRON_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
  cat > .env.local <<EOF
# Local development environment (Cloud Agent) — generated by .cursor/install.sh.
# No schema query param: the Prisma datasource uses multiSchema
# (schemas = ["visionquest"]) and the pgvector type resolves via the default
# "\$user", public search_path — mirroring the Supabase production setup.
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}"
DIRECT_URL="postgresql://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}"

JWT_SECRET="${JWT_SECRET}"
TEACHER_KEY="${TEACHER_KEY}"
ADMIN_KEY="${ADMIN_KEY}"
API_KEY_ENCRYPTION_KEY="${API_KEY_ENCRYPTION_KEY}"
APP_BASE_URL="http://localhost:3000"
CRON_SECRET="${CRON_SECRET}"

LOG_LEVEL="info"
# Add GEMINI_API_KEY here (or via the in-app Program Setup > AI Provider UI)
# to enable Sage chat and AI extraction. The rest of the app runs without it.
EOF
  echo "    Generated .env.local with fresh local secrets."
else
  echo "    .env.local already present — leaving it untouched."
fi

# Load the local env so Prisma commands see DATABASE_URL/DIRECT_URL.
set -a
# shellcheck disable=SC1091
. ./.env.local
set +a

echo "==> [install] Installing Node dependencies (npm ci)"
npm ci

echo "==> [install] Generating the Prisma client"
npx prisma generate

echo "==> [install] Applying database migrations"
npx prisma migrate deploy

echo "==> [install] Seeding idempotent reference data"
npm run db:seed
# Grounding documents (RAG) — safe upsert; tolerate absence of the inventory.
npm run db:seed-documents || echo "    db:seed-documents skipped (non-fatal)."

echo "==> [install] Done."
