import { createHash } from "crypto";
import { prismaAdmin as prisma } from "@/lib/db";
import { getConfigValue, getPlainConfigValue } from "@/lib/system-config";
import { resolveLocalAiAuthMode } from "./local-auth";
import type { Session } from "@/lib/api-error";

type ControlStatus = "pass" | "warn" | "info";

export interface AiSafetyControl {
  label: string;
  status: ControlStatus;
  detail: string;
}

export interface AiSafetyReport {
  generatedAt: string;
  periodStart: string;
  periodEnd: string;
  periodDays: number;
  generatedBy: {
    id: string;
    role: string;
    displayName: string;
  };
  configuration: {
    activeProvider: string;
    localEndpoint: string;
    localModel: string;
    localAuthMode: string;
    localAuthConfigured: boolean;
    geminiKeyConfigured: boolean;
    geminiKeySource: "system_config" | "environment" | "none";
    compactPromptForLocal: boolean;
    publicFormBypass: boolean;
    codeVersion: string;
  };
  auditSummary: {
    totalAiEvents: number;
    routedEvents: number;
    completedEvents: number;
    directNoModelEvents: number;
    blockedEvents: number;
    failedEvents: number;
    sensitiveLocalRoutes: number;
    sensitiveCloudRoutes: number;
    publicCloudRoutes: number;
    configChanges: number;
  };
  controls: AiSafetyControl[];
  recommendations: string[];
  reportText: string;
  reportHash: string;
}

interface ParsedAuditEvent {
  action: string;
  metadata: Record<string, unknown>;
}

function asString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

function parseMetadata(raw: string | null): Record<string, unknown> {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

function safeEndpointLabel(url: string | null): string {
  if (!url) return "Not configured";
  try {
    const parsed = new URL(url);
    return parsed.origin;
  } catch {
    return "Configured, but URL could not be parsed";
  }
}

function getCodeVersion(): string {
  return (
    process.env.RENDER_GIT_COMMIT ||
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.GIT_SHA ||
    process.env.COMMIT_SHA ||
    "unknown"
  );
}

function countEvents(
  events: ParsedAuditEvent[],
  predicate: (event: ParsedAuditEvent) => boolean,
): number {
  return events.filter(predicate).length;
}

function formatStatus(status: ControlStatus): string {
  if (status === "pass") return "PASS";
  if (status === "warn") return "REVIEW";
  return "INFO";
}

function buildReportText(report: Omit<AiSafetyReport, "reportText" | "reportHash">): string {
  const lines = [
    "VisionQuest AI Student Information Protection Audit Report",
    `Generated: ${new Date(report.generatedAt).toLocaleString("en-US")}`,
    `Generated by: ${report.generatedBy.displayName} (${report.generatedBy.role})`,
    `Audit window: ${new Date(report.periodStart).toLocaleDateString("en-US")} - ${new Date(report.periodEnd).toLocaleDateString("en-US")}`,
    `Code version: ${report.configuration.codeVersion}`,
    "",
    "Executive Summary",
    "VisionQuest classifies AI work by data sensitivity before selecting a model. Student-record and staff-entered tasks are local-only and must use the Ollama provider. Public program tasks may use Gemini, and blank form lookup bypasses AI entirely when the deterministic form registry can answer the request.",
    "",
    "Current Configuration",
    `Active provider setting: ${report.configuration.activeProvider}`,
    `Local Ollama endpoint: ${report.configuration.localEndpoint}`,
    `Local model: ${report.configuration.localModel}`,
    `Local endpoint auth: ${report.configuration.localAuthMode}`,
    `Local auth material configured: ${report.configuration.localAuthConfigured ? "yes" : "no"}`,
    `Gemini API key configured: ${report.configuration.geminiKeyConfigured ? "yes" : "no"}`,
    `Gemini key source: ${report.configuration.geminiKeySource}`,
    `Compact local prompts enabled: ${report.configuration.compactPromptForLocal ? "yes" : "no"}`,
    `Public blank-form AI bypass enabled: ${report.configuration.publicFormBypass ? "yes" : "no"}`,
    "",
    "AI Audit Counts",
    `Total AI audit events: ${report.auditSummary.totalAiEvents}`,
    `Routed model decisions: ${report.auditSummary.routedEvents}`,
    `Completed model requests: ${report.auditSummary.completedEvents}`,
    `Direct no-model responses: ${report.auditSummary.directNoModelEvents}`,
    `Blocked requests: ${report.auditSummary.blockedEvents}`,
    `Failed requests: ${report.auditSummary.failedEvents}`,
    `Sensitive routes handled locally: ${report.auditSummary.sensitiveLocalRoutes}`,
    `Sensitive routes sent to cloud: ${report.auditSummary.sensitiveCloudRoutes}`,
    `Public/program routes sent to cloud: ${report.auditSummary.publicCloudRoutes}`,
    `AI configuration changes in window: ${report.auditSummary.configChanges}`,
    "",
    "Control Results",
    ...report.controls.map(
      (control) => `${formatStatus(control.status)} - ${control.label}: ${control.detail}`,
    ),
    "",
    "Supervisor Notes",
    "This report intentionally does not include raw prompts, responses, student names, resumes, goals, or case notes. AI audit records store routing metadata only: task, sensitivity, provider class, policy decision, status, and size counts.",
    "Gemini is treated as a cloud processor even when connected to a paid Google Cloud billing account. VisionQuest policy reserves Gemini for public/non-student tasks unless the district separately approves sending student-record data to that vendor.",
    "Attach a screenshot or PDF from Google Cloud Console showing active billing for the Gemini API project if this packet is used for a formal audit.",
    "",
    "Reference Materials",
    "FERPA PII definition: https://studentprivacy.ed.gov/content/personally-identifiable-information-education-records",
    "ED online educational services guidance: https://studentprivacy.ed.gov/faq/i-want-use-online-tool-or-application-part-my-course-however-i-am-worried-it-violation-ferpa",
    "FERPA recordkeeping: https://www.ecfr.gov/current/title-34/subtitle-A/part-99/subpart-D/section-99.32",
    "Gemini API terms: https://ai.google.dev/gemini-api/terms",
    "",
    "Recommended Next Evidence",
    ...report.recommendations.map((item) => `- ${item}`),
  ];

  return lines.join("\n");
}

export async function generateAiSafetyReport(
  session: Session,
  periodDays = 30,
): Promise<AiSafetyReport> {
  const now = new Date();
  const boundedDays = Math.min(Math.max(periodDays, 1), 365);
  const periodStart = new Date(now.getTime() - boundedDays * 24 * 60 * 60 * 1000);

  const [
    provider,
    localUrl,
    localModel,
    authModeRaw,
    localBearer,
    cloudflareClientId,
    cloudflareClientSecret,
    systemGeminiKey,
    auditLogs,
    configLogs,
  ] = await Promise.all([
    getPlainConfigValue("ai_provider"),
    getPlainConfigValue("ai_provider_url"),
    getPlainConfigValue("ai_provider_model"),
    getPlainConfigValue("ai_provider_auth_mode"),
    getConfigValue("ai_provider_api_key"),
    getConfigValue("ai_provider_cloudflare_access_client_id"),
    getConfigValue("ai_provider_cloudflare_access_client_secret"),
    getConfigValue("gemini_api_key"),
    prisma.auditLog.findMany({
      where: {
        targetType: "ai_request",
        createdAt: { gte: periodStart, lte: now },
      },
      select: { action: true, metadata: true },
      orderBy: { createdAt: "desc" },
    }),
    prisma.auditLog.findMany({
      where: {
        createdAt: { gte: periodStart, lte: now },
        OR: [
          { action: { startsWith: "admin.ai_provider" } },
          { action: { startsWith: "admin.ai_config" } },
        ],
      },
      select: { id: true },
    }),
  ]);

  const events = auditLogs.map((log) => ({
    action: log.action,
    metadata: parseMetadata(log.metadata),
  }));
  const isSensitive = (event: ParsedAuditEvent) => {
    const sensitivity = asString(event.metadata.sensitivity);
    return sensitivity === "student_record" || sensitivity === "staff_entered";
  };
  const providerClass = (event: ParsedAuditEvent) => asString(event.metadata.providerClass);
  const activeProvider = provider === "local" ? "local" : "cloud";
  const authMode = resolveLocalAiAuthMode(authModeRaw);
  const localAuthConfigured =
    authMode === "none"
      ? true
      : authMode === "bearer"
        ? Boolean(localBearer)
        : Boolean(cloudflareClientId && cloudflareClientSecret);
  const geminiKeySource: AiSafetyReport["configuration"]["geminiKeySource"] = systemGeminiKey
    ? "system_config"
    : process.env.GEMINI_API_KEY
      ? "environment"
      : "none";

  const auditSummary = {
    totalAiEvents: events.length,
    routedEvents: countEvents(events, (event) => event.action === "ai.request.routed"),
    completedEvents: countEvents(events, (event) => event.action === "ai.request.completed"),
    directNoModelEvents: countEvents(events, (event) => event.action === "ai.request.direct"),
    blockedEvents: countEvents(events, (event) => event.action === "ai.request.blocked"),
    failedEvents: countEvents(events, (event) => event.action === "ai.request.failed"),
    sensitiveLocalRoutes: countEvents(
      events,
      (event) => event.action === "ai.request.routed" && isSensitive(event) && providerClass(event) === "local",
    ),
    sensitiveCloudRoutes: countEvents(
      events,
      (event) => event.action === "ai.request.routed" && isSensitive(event) && providerClass(event) === "cloud",
    ),
    publicCloudRoutes: countEvents(
      events,
      (event) =>
        event.action === "ai.request.routed" &&
        asString(event.metadata.sensitivity) === "public_program" &&
        providerClass(event) === "cloud",
    ),
    configChanges: configLogs.length,
  };

  const controls: AiSafetyControl[] = [
    {
      label: "Sensitive tasks are local-only",
      status: auditSummary.sensitiveCloudRoutes === 0 ? "pass" : "warn",
      detail:
        auditSummary.sensitiveCloudRoutes === 0
          ? "No student-record or staff-entered AI route decisions in this window used a cloud provider."
          : `${auditSummary.sensitiveCloudRoutes} sensitive route decision(s) used a cloud provider and require review.`,
    },
    {
      label: "Local Ollama endpoint configured",
      status: localUrl ? "pass" : "warn",
      detail: localUrl
        ? "A local AI endpoint is configured for local-only Sage work."
        : "No local AI endpoint is configured; sensitive AI work will fail closed.",
    },
    {
      label: "Local endpoint authentication",
      status: localAuthConfigured ? "pass" : "warn",
      detail:
        authMode === "none"
          ? "No endpoint auth mode is configured; use Cloudflare Access service tokens for production tunnel traffic."
          : localAuthConfigured
            ? `Required ${authMode} credentials are present.`
            : `The ${authMode} mode is selected, but required credentials are missing.`,
    },
    {
      label: "Gemini cloud use is bounded",
      status: geminiKeySource === "none" ? "info" : "pass",
      detail:
        geminiKeySource === "none"
          ? "No Gemini key is configured, so cloud AI cannot be used through the platform key."
          : "Gemini is available, but VisionQuest policy treats it as cloud-only for public/non-student tasks unless separately approved.",
    },
    {
      label: "Direct form retrieval bypasses AI",
      status: "pass",
      detail: "Blank public form requests are answered from the SPOKES form registry without sending the request to Gemini or Ollama when matched.",
    },
    {
      label: "FERPA-safe audit logging",
      status: auditSummary.totalAiEvents > 0 ? "pass" : "info",
      detail:
        auditSummary.totalAiEvents > 0
          ? "AI audit events were recorded without prompt or response content."
          : "No AI audit events were recorded in this period yet; future requests will populate this report.",
    },
  ];

  const recommendations = [
    "Keep the Google Cloud Console billing screenshot with this report when sharing it with supervisors.",
    "Review this report monthly and after any AI provider setting change.",
    "Use Cloudflare Tunnel plus Cloudflare Access service tokens for production Ollama access.",
    "Investigate any future sensitive-cloud route count above zero before treating the system as audit-ready.",
  ];

  const baseReport = {
    generatedAt: now.toISOString(),
    periodStart: periodStart.toISOString(),
    periodEnd: now.toISOString(),
    periodDays: boundedDays,
    generatedBy: {
      id: session.id,
      role: session.role,
      displayName: session.displayName,
    },
    configuration: {
      activeProvider,
      localEndpoint: safeEndpointLabel(localUrl),
      localModel: localModel || "gemma4:26b",
      localAuthMode: authMode,
      localAuthConfigured,
      geminiKeyConfigured: geminiKeySource !== "none",
      geminiKeySource,
      compactPromptForLocal: true,
      publicFormBypass: true,
      codeVersion: getCodeVersion(),
    },
    auditSummary,
    controls,
    recommendations,
  };
  const reportText = buildReportText(baseReport);
  const reportHash = createHash("sha256").update(reportText).digest("hex");

  return {
    ...baseReport,
    reportText,
    reportHash,
  };
}
